"""add user profile bio, is_admin and photo url fields

Revision ID: 00e19f0bc9ec
Revises: 58d15608267a
Create Date: 2026-09-13 15:45:04.818050

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "00e19f0bc9ec"
down_revision = "58d15608267a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_admin", sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(sa.Column("bio", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("profile_picture", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("profile_picture")
        batch_op.drop_column("bio")
        batch_op.drop_column("is_admin")

    # ### end Alembic commands ###
