"""Initial migration.

Revision ID: 205ff418d049
Revises:
Create Date: 2026-08-30 13:43:44.729584

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "205ff418d049"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("first_name", existing_type=sa.VARCHAR(length=100), nullable=True)
        batch_op.alter_column("last_name", existing_type=sa.VARCHAR(length=100), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("last_name", existing_type=sa.VARCHAR(length=100), nullable=False)
        batch_op.alter_column("first_name", existing_type=sa.VARCHAR(length=100), nullable=False)

    # ### end Alembic commands ###
