"""Add created_at to users

Revision ID: 58d15608267a
Revises: 205ff418d049
Create Date: 2026-08-30 13:47:45.889217

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "58d15608267a"
down_revision = "205ff418d049"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.func.now(),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
