"""update blog and post relationships

Revision ID: 79a459622d0c
Revises: 1056c74459ae
Create Date: 2026-09-27 16:11:19.371440

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "79a459622d0c"
down_revision = "1056c74459ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("blog_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["blog_id"],
            ["blogs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("blog")
    with op.batch_alter_table("blogs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("title", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("category", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("description", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=False))
        batch_op.drop_constraint(batch_op.f("blogs_email_key"), type_="unique")
        batch_op.drop_constraint(batch_op.f("blogs_username_key"), type_="unique")
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])
        batch_op.drop_column("username")
        batch_op.drop_column("password")
        batch_op.drop_column("email")
        batch_op.drop_column("bio")
        batch_op.drop_column("last_name")
        batch_op.drop_column("is_admin")
        batch_op.drop_column("first_name")
        batch_op.drop_column("profile_picture")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("first_name", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("last_name", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("last_name", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("first_name", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("blogs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("profile_picture", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("first_name", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("is_admin", sa.BOOLEAN(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(sa.Column("bio", sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(
            sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")  # ty: ignore[invalid-argument-type]
        batch_op.create_unique_constraint(
            batch_op.f("blogs_username_key"), ["username"], postgresql_nulls_not_distinct=False
        )
        batch_op.create_unique_constraint(
            batch_op.f("blogs_email_key"), ["email"], postgresql_nulls_not_distinct=False
        )
        batch_op.drop_column("updated_at")
        batch_op.drop_column("description")
        batch_op.drop_column("category")
        batch_op.drop_column("title")
        batch_op.drop_column("user_id")

    op.create_table(
        "blog",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("first_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("is_admin", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("bio", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("profile_picture", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("blog_pkey")),
        sa.UniqueConstraint(
            "email",
            name=op.f("blog_email_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "username",
            name=op.f("blog_username_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table("posts")
    # ### end Alembic commands ###
